### ISSUE TITLE
A question about train_gta2city.py

### ISSUE THREAD

**Issue by DHuiTnut** [idealwei/ASANet#1]
Hi, what a great work! I'm insterested in your work. 

In line160, if "source_label" should be replaced with "target_label"? 
 https://github.com/idealwei/ASANet/blob/9f9fb7da15fe7375b36a3bb1ad14393f2e38c9a4/train_gta2city.py#L160

**Comment by idealwei** [comment]
No. We apply adv loss to make the segmentation network generate source-image-style affinity space for target image.
